### ISSUE TITLE
Fix initial value on Akvo React Form

### ISSUE THREAD

**Issue by ifirmawan** [akvo/akvo-react-form#139]
## TODO/DONE

- [x] Fix initial value
- [x] Fix handle get questions in TypeAutofield
- [x] Remove unnecessary questions
